spring:
  application:
    name: testone-service
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://192.168.1.58:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username:  root
    password:  P@ssword123
    driver-class-name:  com.mysql.jdbc.Driver
mybatis:
    mapperLocations:  classpath:mybatis/mapper/mysql/*.xml
    typeAliasesPackage: framework.lisi.entity
    configLocation: classpath:mybatis/mybatis-config.xml
security:
    oauth2:
        client:
          client-id: my-trusted-client
          client-secret: 123456
          access-token-uri: http://localhost:9999/uaa/oauth/token
          user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
        resource:
            userInfoUri:  http://localhost:9999/uaa/user
server:
  port: 3333
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
