spring:
  application:
    name: auth-service
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://192.168.1.58:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username:  root
    password:  P@ssword123
    driver-class-name:  com.mysql.jdbc.Driver
  redis:
    cluster:
      nodes:
        - 192.168.1.67:9001
        - 192.168.1.67:9002
        - 192.168.1.67:9003
    
management:
  context_path: /admin
  
security:
  oauth2:
      resource:
        filter-order: 3
        userInfoUri: http://localhost:9999/uaa/user
spring:

mybatis:
    mapperLocations:  classpath:mybatis/mapper/mysql/*.xml
    typeAliasesPackage: framework.lisi.entity
    configLocation: classpath:mybatis/mybatis-config.xml
server:
  port: 9999
  contextPath: /uaa
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
